trigger: none
pr: none
pool:
  vmImage: 'ubuntu-latest'
schedules: 
- cron: '45 16 * * *'
  displayName: Daily snapshot
  branches:
   include:
   - main
  always: true

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'SNAPSHOT_DEMO'
    scriptType: bash 
    scriptLocation: inlineScript
    inlineScript: |
      az account show
      
      if ! [ -f resource-groups.txt ]; then
        echo "Please provide resource-groups.txt file with resource groups listed on a single line for each"
        exit 1
      fi
      cat resource-groups.txt | while read RG
      do
        ./az-snap-disk -i -g $RG
      done
